### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by kornelski** [jameysharp/corrode#10]
I know how to run C and Rust code, but with Haskell… I don't know where to start. Could you add "How to run this for C coders" instructions?

**Comment by bandali** [comment]
@pornel here you go #11 :smiley:.

If you'd like to get started before the PR is merged, be sure to either copy the `stack.yaml` from my PR to the root of the project or generate it yourself by running `stack init` before trying to build or install.

**Comment by jameysharp** [comment]
That's a quite sensible request, @pornel, which I had intended to do but forgot about. Thanks for the reminder!

And obviously, thanks to @aminb for actually writing clear instructions; mine would probably not have been this good. :smile:

@pornel, if you run into any trouble with these instructions, please say so; or if you see a way to make them more clear, please submit a pull request. I would definitely like for folks to be able to use this project without having to be familiar with the Haskell ecosystem first!

**Comment by kornelski** [comment]
Thank you very much. I'm hopefully going to give it a try this weekend!

**Comment by bandali** [comment]
@jameysharp @pornel You're very welcome, glad I could help.
