### ISSUE TITLE
Enum values are not handled in constant position

### ISSUE THREAD

**Issue by Marwes** [jameysharp/corrode#107]
Tried running corrode on lua but that failed due to its use of enum values to specify array sizes.

### Input
```c
enum Test {
    X = 1,
};

struct Struct {
    char array[X];
};

struct Struct test() {
    
}
```

### Expected
```rust
enum Test {
    X = 1,
}

#[derive(Clone, Copy)]
#[repr(C)]
pub struct Struct {
    pub array : [u8; Test::X as usize],
}

#[no_mangle]
pub unsafe extern fn test() -> Struct { }
```

**Comment by jameysharp** [comment]
Thank you for an excellently clear bug report!

Today @ranweiler and I tried to make this work, but there's a surprising amount going on there and we gave up for today.

This will get fixed eventually though, I promise. :-) Until then, I'm tracking these issues in #52.
