### ISSUE TITLE
Ambassador of pain: unconsumed blocks

### ISSUE THREAD

**Issue by vi** [jameysharp/corrode#108]
```c
int main() {
    start:
    if (0) { return 1; }
    for(;;) break;
    do {
        if (1) {
            goto start;
        }
        else if (0) {
            if(0) { break; }
            continue;
        }
    } while( 1 );
    return 0;
}
```

```
<command-line>:0:1: warning: undefining "__LINE__"
("bug.c": line 1): unconsumed blocks: [0,5]:
    start @0
    0:  if(0i32) goto 6; else goto 1;
    
    1:  if(1i32) goto 0; else goto 2;
    
    2:  if(0i32) goto 3; else goto 4;
    
    3:  if(0i32) goto 5; else goto 4;
    
    4:  if(1i32) goto 1; else goto 5;
    
    5:  return 0i32;
        // unreachable
    
    6:  return 1i32;
        // unreachable
    
from:
    main()
```

Minimized from `aop.c` from [this archive](http://raffi.at/code/aop/aop-0.6.tar.gz).

If get rid of second `break` (replacing with flag variable), use `char**argv`, and initialize those chars then I the resulting code builds and runs. Is it the first corroded game?

**Comment by jameysharp** [comment]
I'm pretty sure this is an example of "irreducible" control flow, which the code currently on master just can't handle.

I'm working on a new implementation that should handle any control flow, but haven't got enough bugs out of it yet. Still, you could try the wip-cfg branch if you want!

**Comment by jameysharp** [comment]
This should be working correctly now! I've merged the wip-cfg branch (after fixing lots of bugs in it).

**Comment by vi** [comment]
Verified that it works (after I change `char *argv[]` to `char** argv` and fill in the uninitialized variables). Maybe Corrode can fill in uninitialized things with `::std::mem::uninitialized()` when needed automatically?
