### ISSUE TITLE
Why not clang?

### ISSUE THREAD

**Issue by lylemoffitt** [jameysharp/corrode#114]
I love what you're doing and hope to see this project one day cover C++ conversions as well. However, I'm worried that you'll ever get there though, because the transforms you apply to your front-end [dependency](http://hackage.haskell.org/package/language-c) probably (?) won't be translatable or reusable in whatever C++ extension that comes later (and so none will). I know theoretically it should be possible, given that C is a subset of C++, but API differences blah, blah, blah, and so on.

Anyway... I was wondering why you didn't just use  [libclang](http://clang.llvm.org/doxygen/group__CINDEX.html). It's even got Haskell bindings through [clang-pure](http://hackage.haskell.org/package/clang-pure). This should theoretically get you access to a whole bunch of other features in time, like: comment transforming, advanced type information (for when you get converting to Rust types), and source-code lookup for diagnostics and help messages. Otherwise you'd be reinventing those features yourself. I know parsing the AST directly would be more daunting, but [Clang AST](http://clang.llvm.org/docs/IntroductionToTheClangAST.html) isn't *that* bad, and I think provides a lot of benefit for its cost.

> As an aside, the AST info could also be made available (albieti in a more limited fashion) with GCC-XML (now [CastXML](https://github.com/CastXML/CastXML)) if you wanted to integrate through XML rather then C++.

**Comment by jameysharp** [comment]
Thanks for the suggestion! I did try libclang first, as it happens, and from Rust rather than Haskell. It turns out that although clang is a good C compiler, libclang is useless for this project. It doesn't expose enough of the AST through its C API. So I chose a C parser that I knew would work, which happened to mean Haskell.

I would like to consider clang's C++ "libtooling" API though, at some point… I'd also be willing to consider either of the XML formats you mentioned or other options. These aren't a high priority for me yet, though, since there's so much left to translate as it stands now.

**Comment by lylemoffitt** [comment]
>It doesn't expose enough of the AST through its C API.

Thanks for taking the time. If you could, would you please elaborate on what AST elements are missing  that you needed? I've never used either libclang or the haskell library you're using for parsing, but my understanding is that both expose a complete AST, they just tokenize it differently.

**Comment by jameysharp** [comment]
libclang is a C wrapper around clang's C++ implementation. The C++ AST is complete (I assume, given that clang uses it) but it does not have a stable API; it changes with every major release of the compiler. To support tools like IDEs, the clang developers created libclang as a C wrapper with a stable API. However, they only exposed enough to do common IDE actions like code search and syntax checking.

By contrast, language-c is an entirely separate project, developed independently in Haskell. The two projects do not share ASTs or anything else.

**Comment by lylemoffitt** [comment]
Ah. Thank you again for taking the time. I wasn't aware enough of the differences in the backends. From the name alone I would have thought that LibTooling was intended for IDE integration, and that LibClang would be the most complete. But now that you mention it, I was able to find a statement from [LLVM](https://clang.llvm.org/docs/Tooling.html) that explains a bit more of why this isn't the case. Seeing this it's now a lot clearer that because what you need is access to the AST that is both **stable** and **complete**, there is nothing that LLVM offers that can really fill your needs. LibTooling is complete but not stable, and LibClang is stable but not complete.

> I would like to consider clang's C++ "libtooling" API though, at some point…

Given the reasoning that I've now laid out, would it be correct to say that what you're waiting for is a stable AST in LibTooling?
