### ISSUE TITLE
Update GHC ?

### ISSUE THREAD

**Issue by flip111** [jameysharp/corrode#125]
Maybe it would be nice to depend on LTS 8.* instead of 6.6 ?

**Comment by jameysharp** [comment]
Apparently @pfasante agreed with you, because #131 switched us to LTS 8.5. I don't actually know what that does since I don't use Stack, but hopefully it works for you!

**Comment by flip111** [comment]
It upgrades ghc from 7.10.3 to 8.0.2 and update packages to a new lts release, see for package difference https://www.stackage.org/diff/lts-6.6/lts-8.5
