### ISSUE TITLE
dependency mismatch: language-c-0.5.0 must match ==0.6.* (latest applicable is 0.6.1)

### ISSUE THREAD

**Issue by pfasante** [jameysharp/corrode#129]
I did a clean git clone of the project, stack setup and stack build. The last step fails, because my language-c version is not new enough. As far as I understand stack, this should be covered by the chosen resolver.

> % git clone https://github.com/jameysharp/corrode
> Cloning into 'corrode'...
> remote: Counting objects: 2381, done.
> remote: Total 2381 (delta 0), reused 0 (delta 0), pack-reused 2381
> Receiving objects: 100% (2381/2381), 631.88 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (798/798), done.
> Checking connectivity... done.

> % stack setup
> stack will use a sandboxed GHC it installed
> For more information on paths, see 'stack path' and 'stack exec env'
> To use this GHC and packages outside of a project, consider using:
> stack ghc, stack ghci, stack runghc, or stack exec

> % cat stack.yaml | grep "resolver: lts-6"
> resolver: lts-6.6

> % stack ghc -- --version
> The Glorious Glasgow Haskell Compilation System, version 7.10.3

> % stack build
> 
> Error: While constructing the build plan, the following exceptions were encountered:
> 
> In the dependencies for corrode-0.1.0.0:
>     language-c-0.5.0 must match ==0.6.* (latest applicable is 0.6.1)
> 
> Plan construction failed.
> [1]    18829 exit 1     stack build

**Comment by jameysharp** [comment]
Fixed by merging #131. Thanks!
