### ISSUE TITLE
implement sizeof/alignof for expressions

### ISSUE THREAD

**Issue by jameysharp** [jameysharp/corrode#13]
The `CSizeofExpr` and `CAlignofExpr` constructors of [`CExpression`](https://hackage.haskell.org/package/language-c-0.5.0/docs/Language-C-Syntax-AST.html#t:CExpression) should be translated almost identically to the `CSizeofType` and `CAlignofType` constructors, respectively, except that the expression needs to be translated using `interpretExpr`.

However, I'm not sure about the exact translation. There are two possibilities:
1. If the expression is supposed to have its side effects evaluated, then we should pass a borrow of the resulting expression to [`std::mem::size_of_val`](https://doc.rust-lang.org/stable/std/mem/fn.size_of_val.html).
2. Otherwise, if side effects are not supposed to be evaluated, we should just use the `resultType` from translating the expression, throwing away the expression itself, and proceed just like `CSizeofType`/`CAlignofType`.

Before trying to implement this, we need a citation to C99 or C11 which clarifies whether the expression should actually be evaluated.

**Comment by eefriedman** [comment]
> we need a citation to C99 or C11 which clarifies whether the expression should actually be evaluated.

This is C11 6.5.3.4 ("The sizeof and _Alignof operators").

For sizeof: "If the type of the operand is a variable length array type, the operand is evaluated; otherwise, the operand is not evaluated and the result is an integer constant."

For alignof: "The operand is not evaluated and the result is an integer constant"

**Comment by jameysharp** [comment]
Thank you, @eefriedman! Hopefully someone can easily implement the specified behavior now.

**Comment by lamarqua** [comment]
A quick remark in the case of VLAs, [as per the previous comment](https://github.com/jameysharp/corrode/issues/13#issuecomment-231423099), we will need to use the expression used to compute the length of the array. I haven't checked exactly what the standard says, but if the expression is a complex one with potential side effects, it needs to be cached for all subsequent sizeofs: 

```
void variable_size() {
    static size_t ret = 0;
    ret++;
    return ret;
}

void f() {
    int array[variable_size()];
    size_t a = sizeof array, b = sizeof array; // at this point we should expect a == b
}
```

**Comment by fanzier** [comment]
To implement this, one would first have to implement a proper translation of arrays (i.e. not as simply a pointer, as described in https://github.com/jameysharp/corrode/issues/52#issuecomment-235823018), correct?

**Comment by jameysharp** [comment]
Good question! Variable length arrays, in particular, are going to be challenging, as @lamarqua pointed out; but it's OK to just ignore them, at least for now.

Regarding fixed-size arrays, I think you can implement this independently of that. Corrode will generate the wrong code when translating sizeof expressions involving arrays, just like it does for other things involving arrays… but my guess is that when array handling gets fixed later, the code for `CSizeofExpr` won't have to change at all.

So I suggest you go ahead and take care of this one, and not worry about how it interacts with arrays. We can fix up that aspect later if necessary.

**Comment by fanzier** [comment]
OK, sounds good! Gonna work on it tomorrow.

**Comment by jameysharp** [comment]
Nice work! Merged. Thanks!
