### ISSUE TITLE
Break not inserted into for loop

### ISSUE THREAD

**Issue by danielrh** [jameysharp/corrode#130]
This simple code does not produce the correct output
```
    for (int i = 0;i < num_clusters;++i) {
        if (clusters[i] == best_index) {
            fake_memmove(&clusters[i],
                    &clusters[i+1],
                    (num_clusters - i- 1)* sizeof(clusters[0]));
            break;
        }
    }
```

the break is omitted from the output code

```
    let mut i : i32 = 0i32;
    'loop1: loop {
        if i < num_clusters {
            if clusters[i as (usize)] == best_index {
                fake_memmove(
                    &mut clusters[
                             i as (usize)
                         ] as (*mut u32) as (*mut ::std::os::raw::c_void),
                    &mut clusters[
                             (i + 1i32) as (usize)
                         ] as (*mut u32) as (*mut ::std::os::raw::c_void),
                    ((num_clusters - i - 1i32) as (usize)).wrapping_mul(
                        ::std::mem::size_of::<u32>()
                    )
                );
            } else {
                i = i + 1;
                continue 'loop1;
            }
        } else {
            break 'loop1;
        }
    }
```

A fix would be appreciated: I've been using corrode to translate the brotli encoder and I'm worried I've hit this situation more than once

**Comment by danielrh** [comment]
[test.c.txt](https://github.com/jameysharp/corrode/files/857230/test.c.txt)
[test.rs.txt](https://github.com/jameysharp/corrode/files/857231/test.rs.txt)

**Comment by danielrh** [comment]
Here's a link to the file "in the wild" https://github.com/dropbox/rust-brotli/blob/encoder/corrosion/cluster.rs
you can find by searching memmove
the original is here
https://github.com/danielrh/brotli/blob/corrode/enc/cluster.c

**Comment by danielrh** [comment]
got an even simpler test:
```
void side_effect(int i){}
int main() {
    for (int i = 0;  i < 10; ++i) {
        if (i == 3) {
            side_effect(i);
            break;
        }
        if (i>=3) {
            return 1;
        }
    }
    return 0;
}
```
removing side_effect(i) fixes the program to do the correct thing. In this case side_effect has no effect ;-)

**Comment by danielrh** [comment]
The output is actually very strange. the i >=3 gets put in an else if, and the result infinite loops

```
pub unsafe extern fn side_effect(mut i : i32) { }

fn main() {
    let ret = unsafe { _c_main() };
    ::std::process::exit(ret);
}

#[no_mangle]
pub unsafe extern fn _c_main() -> i32 {
    let mut i : i32 = 0i32;
    'loop1: loop {
        if i < 10i32 {
            if i == 3i32 {
                side_effect(i);
            } else if i >= 3i32 {
                return 1i32;
            } else {
                i = i + 1;
                continue 'loop1;
            }
        } else {
            break 'loop1;
        }
    }
    0i32
}
```

**Comment by danielrh** [comment]
Came up with an even more minimal example. I'm priting out the depthFirstOrder of the blocks

[test3_rs.txt](https://github.com/jameysharp/corrode/files/863416/test3_rs.txt)
[test3.txt](https://github.com/jameysharp/corrode/files/863418/test3.txt)
```
int main() {
    int i = 0;
    while (i < 10) {
        if (i == 3) {
            i += 2;
            if (!0) {
                break;
            }
        }
        i += 1;
    }
  loopend:
    return !(i < 10);
}
```
```
    start @0
    0:  let mut i : i32 = 0i32;
        goto 1;
    
    1:  if(i < 10i32) goto 2; else goto 5;
    
    2:  if(i == 3i32) goto 3; else goto 4;
    
    3:  i = i + 2i32;
        if(0i32 == 0) goto 5; else goto 4;
    
    4:  i = i + 1i32;
        goto 1;
    
    5:  return !(i < 10i32) as (i32);
        // unreachable
```
becomes
```
pub unsafe extern fn _c_main() -> i32 {
    let mut i : i32 = 0i32;
    'loop1: loop {
        if i < 10i32 {
            if i == 3i32 {
                i = i + 2i32;
                if 0i32 == 0 {
                    break 'loop1;
                }
            }
            i = i + 1i32;
            continue 'loop1;
        } else {
            break 'loop1;
        }
    }
    !(i < 10i32) as (i32)
}
```
vs
```
int main() {
    int i = 0;
    while (i < 10) {
        if (i == 3) {
            i += 2;
            break;
        }
        i += 1;
    }
  loopend:
    return !(i < 10);
}
```

```
("test4.c": line 1): OK:
    start @0
    0:  let mut i : i32 = 0i32;
        goto 1;
    
    1:  if(i < 10i32) goto 2; else goto 5;
    
    2:  if(i == 3i32) goto 4; else goto 3;
    
    3:  i = i + 1i32;
        goto 1;
    
    4:  i = i + 2i32;
        goto 5;
    
    5:  return !(i < 10i32) as (i32);
        // unreachable
    
from:
    main()
```
becomes (broken)
```
pub unsafe extern fn _c_main() -> i32 {
    let mut i : i32 = 0i32;
    'loop1: loop {
        if i < 10i32 {
            if i == 3i32 {
                i = i + 2i32;
            } else {
                i = i + 1i32;
                continue 'loop1;
            }
        } else {
            break 'loop1;
        }
    }
    !(i < 10i32) as (i32)
}
```
[test4_rs.txt](https://github.com/jameysharp/corrode/files/863415/test4_rs.txt)
[test4.txt](https://github.com/jameysharp/corrode/files/863417/test4.txt)

**Comment by aeyakovenko** [comment]
I poked around the code a bit.  it looks like `breaks = IntMap.map IntSet.findMax (IntMap.fromListWith IntSet.union breakList` in `CFG.unifyBreaks` eats that jump.  I don't entirely follow how the Branch labels correspond to the conditionals.  I added a bunch of traces in https://github.com/aeyakovenko/corrode/tree/debug .  I think i just need to try manufacturing a CFG that has a loop with a conditional break and see whats different from the parsed one.

@jameysharp this is a super cool project!  one thing that i think might make it easier to follow is a separate data structure for the optimization pass.  `CFG -> Optimized` `Optimized -> CFG`, where Optimized is a flattened result of all computations you are doing to do the optimizations.  You can then test that the original CFG computes the same result as the final CFG with a CFG interpreter.  You can still do the same testing with a simple in-place transform `CFG -> CFG`, but having an intermediate makes it easy to follow whats busted.  @garious demonstrated the value of this intermediate data structure to me when we were building an IDL compiler

**Comment by jameysharp** [comment]
Hey @danielrh, thanks for trying Corrode, and for your detailed test notes! And @aeyakovenko, thank you for your suggestions for fixing this bug!

As it happens, I've been working on fixing issues like these since December, and it's been a huge pain, but today I merged the `wip-cfg` branch to master and I believe it fixes all bugs like this one. It's a complete rewrite, following roughly the approach used in Emscripten's "Relooper" algorithm.

@aeyakovenko, you are absolutely right about the value of constructing an intermediate data structure. The new implementation does exactly that, and as you suggest, it was super helpful during debugging. Also, I did write something of a CFG interpreter for the QuickCheck tests that caught a lot of bugs for me. In short, I agree with your suggestions!

I'm report this issue because I believe the issues described should be addressed on master now. If not, feel free to re-open this!
