### ISSUE TITLE
corrode produces if blocks returning values that are not used

### ISSUE THREAD

**Issue by jrmuizel** [jameysharp/corrode#134]
Running the latest corrode with the new cfg stuff on https://pastebin.mozilla.org/9018043 produces rust code that doesn't compile with the following error:

```
error[E0317]: if may be missing an else clause
   --> out.rs:502:16
    |
502 |           } else if _currentBlock == 76 {
    |  ________________^ starting here...
503 | |             *out_len = ((op as (isize)).wrapping_sub(
504 | |                             out as (isize)
505 | |                         ) / ::std::mem::size_of::<u8>() as (isize)) as (usize);
506 | |             -4i32
507 | |         }
    | |_________^ ...ending here: expected (), found i32
    |
    = note: expected type `()`
               found type `i32`
```

the -4i32 seems to be the cause of the problem.

**Comment by jameysharp** [comment]
I haven't looked at the pastebin or tried running Corrode on this myself yet, but based purely on the snippet shown, I'm guessing this is a bug in `src/Language/Rust/Idiomatic.hs`. That module tries to rewrite Rust `return` statements into trailing expressions, and if I didn't get the preconditions right on when that's safe to do, that could cause this.

**Comment by jameysharp** [comment]
No, I'm wrong; the new CFG bits are the best place to fix this. The generated code was correct but not in a way that a compiler could check without invoking an SMT solver, and running that through `Idiomatic` only made it worse. Fix in progress!
