### ISSUE TITLE
implement do-while loops

### ISSUE THREAD

**Issue by jameysharp** [jameysharp/corrode#14]
The `CWhile` constructor of [`CExpression`](https://hackage.haskell.org/package/language-c-0.5.0/docs/Language-C-Syntax-AST.html#t:CExpression) is currently only translated if its `Bool` flag is `False`, meaning this is a regular while-loop which tests the loop condition before entering the loop.

If that flag is `True`, then we need a different translation plan. Since Rust doesn't have do-while loops, we'll have to translate these like this:

``` rust
loop {
    ...
    if !cond { break; }
}
```

But like `for` loops, it's a little trickier than that if the loop contains any `continue` statements. The same strategy we use on `for` loops should work here, though:

``` rust
'breakTo: loop {
    'continueTo: loop {
        ...
        break;
    }
    if !cond { break; }
}
```

Like with `for` loops, `break` and `continue` statements should be translated to `break 'breakTo` and `break 'continueTo`, respectively.

**Comment by lamarqua** [comment]
Hi @jameysharp! Is someone already working on this? I convinced @anniecherk (an RC 'S2) to pair with me on contributions to Corrode. I feel like this would be a good starting place for us.

**Comment by jameysharp** [comment]
You two should do it! Let me know if you have any questions!

For what it's worth, this is blocking translating some of the musl C
library, so I'll have some test cases as soon as you have some patches.
:smile:

**Comment by jdub** [comment]
Would handling the common macro idiom `do { … } while (0);` be a slightly simpler though still widely beneficial step? I suppose it depends if the idiom is used alone, or if there's any use of `break`…

**Comment by jameysharp** [comment]
A fine question, @jdub! I suspect recognizing the `while(0)` idiom is more work than just producing an ugly translation, but I'd probably take a patch either way.

As a very general policy, I'd rather not do any constant-folding transformations like noticing that the literal `0` is always false, because I want to have the generated Rust match the structure of the original C as closely as possible. But maybe the `do { … } while (0);` pattern in particular should be an exception...

**Comment by jdub** [comment]
I reckon your instinct (and design goal!) is right: corrode should translate as-is. In which case, I'll wait to see what @lamarqua and @anniecherk come up with!

**Comment by fanzier** [comment]
Is anyone still working on this? Otherwise I'd have a go at it.

**Comment by jameysharp** [comment]
I haven't heard anything from @lamarqua recently, so I imagine something else came up, as happens to everyone from time to time. :smile: So I'd say, go for it @fanzier!

**Comment by lamarqua** [comment]
Yep, so sorry, I've been away from Haskell for a while :( Life got in the way, but I plan to return to it very soon (in particular the array patch). 
@fanzier you should go for this one!

**Comment by fanzier** [comment]
Just opened a pull request (#62) :)

**Comment by jameysharp** [comment]
I've been testing corrode on musl-libc, and in every case where Corrode was failing on that codebase due to do/while loops, your pull request successfully translates them. Hooray! Sadly, in most of those cases it just means that Corrode fails on something else, but this is still progress. :wink:

On that note, @fanzier, can I suggest you tackle #13 next if you want to hack on Corrode some more? That'll make quite a lot more of musl-libc translate successfully. :smile: Turns out there's an awful lot of C code out there that relies on `sizeof` on expressions, and more than I expected uses `typeof`.

I am delighted by this commit, by the way; it's clean and readable and you did a nice job updating the documentation! I did push a tiny improvement on top of this pull request, in commit f35a34b, to generate loop-termination expressions like `num == 0` rather than `!(num != 0)`; I had previously written a little helper for that so I just reused it here. Otherwise, everything looked good to me!

And @lamarqua, no worries! Let me just say I'm eager to see the array stuff fixed, and if you get to it, that will be awesome. But if life continues to get in the way, well, these things happen!

**Comment by jdub** [comment]
Would you expect this change to handle `do { … } while (0);`? I'm on f35a34bc82081867b4ce83c29004d3e6fe85cc05. This is the same error fragment as before.

```
("../build/x86/pc99/libsel4/include/sel4/shared_types_gen.h": line 19): Corrode doesn't handle this yet:
        do
        {
            if (!((label & ~0xfffffuL) == (0 && label & 1uL << 31 ? 0x0 : 0)))
            {
                __assert_fail("(label & ~0xffffful) == ((0 && (label & (1ul << 31))) ? 0x0 : 0)",
                              "../build/x86/pc99/libsel4/include/sel4/shared_types_gen.h",
                              19,
                              __FUNCTION__);
            }
        }
        while (0);
```

**Comment by jameysharp** [comment]
Hi @jdub! Yes, I would expect `do ... while(0)` to work. Here's a little test I just tried:

``` c
int foo(void) {
    int i = 0;
    do {
        ++i;
    } while(0);
    return i;
}
```

Corrode translated that to:

``` rust
#[no_mangle]
pub unsafe fn foo() -> i32 {
    let mut i : i32 = 0i32;
    loop {
        {
            i = i + 1;
        }
        if 0i32 == 0 {
            break;
        }
    }
    i
}
```

Which seems like what I was expecting, even though the translation is a little ugly in this case.

Did you either `cabal install` or `stack install` after `git pull`?

**Comment by jdub** [comment]
> Did you either `cabal install` or `stack install` after `git pull`?

Yeeeesss, muuuuum! 😆 As it happens, it's on a new VM.

Is there some extra debug goop I can give you?

**Comment by jameysharp** [comment]
You know I was obligated to ask. :wink:

Can you try to reduce the failing loop to a minimal test case? I can't see any reason why it wouldn't work on current master. (Well, `__FUNCTION__` is probably going to lead to trouble later, but it looks like Corrode is failing before it gets there.)

**Comment by jdub** [comment]
Argh! I discovered some muck left around after a previous build (`Main.lhs` and `C.lhs`), which wasn't removed by `cabal clean`. After a `git reset --hard`, our minimal test cases are working and…

… the libsel4 conversion explodes at `__FUNCTION__` as you expected! Yay. 😄

```
("../build/x86/pc99/libsel4/include/sel4/shared_types_gen.h": line 19): illegal undefined variable; check whether a real C compiler accepts this:
    __FUNCTION__
```

**Comment by fanzier** [comment]
@jameysharp I'd definitely like to continue to hack on corrode, as time allows. I'll have a look at the issue you suggested.

Is there a tracking issue for what is needed to translate musl? I imagine we need switch statements as well etc.
