### ISSUE TITLE
Using corrode with cmake

### ISSUE THREAD

**Issue by torkleyy** [jameysharp/corrode#167]
This project looks interesting! Is there a known workaround to use it with CMake? Currently, CMake compiles a test program if you specify a custom compiler, which however fails to compile because it uses `argv[]`.

**Comment by artycorp** [comment]
try CMAKE_C_COMPILER_FORCED:
in CMakeLists.txt
SET(CMAKE_C_COMPILER_FORCED ON)

**Comment by torkleyy** [comment]
`cmake -DCMAKE_C_COMPILER=/home/thomas/.cabal/bin/corrode -DCMAKE_C_COMPILER_FORCED=ON ..`

worked for me, thanks!
