### ISSUE TITLE
__BLOCKS__ is defined, but blocks are not supported

### ISSUE THREAD

**Issue by kornelski** [jameysharp/corrode#27]
When including `MacOSX10.11.sdk/usr/include/stdlib.h`, corrode does not parse the C block syntax extension

>  The symbol `^' does not fit here.

Invoking the compiler with `-U__BLOCKS__` helps, but I think `__BLOCKS__` should be undefined by default.

**Comment by jameysharp** [comment]
First off, it seems like a shame to not support the blocks extension, as I think their semantics would probably be a good fit for Rust's closures. So I'd love to see someone add support for parsing blocks syntax in language-c.

That aside, I assume this is fallout from Apple's decision to make `gcc` a symlink to clang? So when we invoke GCC to preprocess the source we get clang's defaults about which macros to define, and of course clang knows it supports blocks.

At the moment, I think the best option is, like you suggested, to always undefine `__BLOCKS__`. You can do that in Main.hs with something like

``` haskell
args `addCppOption` Undefine "__BLOCKS__"
```

Would you be willing to write such a commit, test that it solves this problem, and send a pull request?

Thanks for trying out Corrode!

**Comment by kornelski** [comment]
Sorry, it's not my cup of tea.

**Comment by jameysharp** [comment]
That's fine. Would you test that the `undef-blocks` branch fixes this problem for you?

**Comment by erszcz** [comment]
@jameysharp I tested it and confirm, `undef-blocks` branch fixes the issue.

Great project idea, by the way!

**Comment by jameysharp** [comment]
Thanks for confirming, and for the compliment! :smile:
