### ISSUE TITLE
Can't corrode a hello world example

### ISSUE THREAD

**Issue by colltoaction** [jameysharp/corrode#29]
Hi,

I tried to compile the following simple program, but I get the following error:

``` c
#include <stdio.h>

int main() {
    printf("Hello World!");
    return 0;
}
```

```
corrode: ("/usr/include/wchar.h": line 85): Corrode doesn't handle this yet:
    union {
        unsigned int __wch; char __wchb[4];
    }
```

Let me know if you need any details about my environment/compiler.

**Comment by jameysharp** [comment]
That's right, it doesn't support C unions yet. I'm tracking that in issue #22.

Meanwhile, instead of including all of `stdio`, you make this example work with:

``` c
extern int printf(const char *fmt, ...);
```

Thanks for trying out Corrode!
