### ISSUE TITLE
Define [repr(C)] on translated structs

### ISSUE THREAD

**Issue by Storyyeller** [jameysharp/corrode#33]
Currently,  Corrode fails to add #[repr(C)] to translated struct definitions, meaning that the generated code does not preserve behavior and cannot interact with C code.

**Comment by jameysharp** [comment]
Good point! This is easily fixed, if you'd like to get a quick pull request in: just look for where the "`derive(Clone, Copy)`" attribute is added, and add "`repr(C)`" to the list as well.

**Comment by Storyyeller** [comment]
I'll look into it tomorrow.

**Comment by jameysharp** [comment]
Perfect, thanks! Merged commit 22c8aa1 fixing this.
