### ISSUE TITLE
license

### ISSUE THREAD

**Issue by Storyyeller** [jameysharp/corrode#36]
It looks like you are using GPL v2. Have you considered adding the "or any later version" option, in order to improve compatibility with other licenses?

**Comment by jameysharp** [comment]
Well, I hadn't thought about it, but now I have. :smile:

I don't think there are any other licenses we need to worry about compatibility with. Corrode is a program; it isn't meant to be linked into a larger project. And Haskell packages are usually licensed under some variant of BSD, MIT, or GPL, all of which are compatible with GPLv2, so practically speaking, I don't expect this license to limit what other libraries we can use.

That said, I would be delighted for someone to extract `Language.Rust.AST` as a separate package and flesh it out to a complete AST, and for that I would suggest either BSD license variant. For that module in particular, I'm happy to relicense my work.

But I'd want a more compelling argument to relicense the rest of Corrode.

Thanks for asking! It's a good question to bring up early.

**Comment by Storyyeller** [comment]
Actually, GPL isn't compatible with GPLv2. Or more specifically, GPLv3 and GPLv2 are incompatible.

**Comment by jameysharp** [comment]
Alright, my mistake. Still, all of Corrode's current dependencies are BSD3 or MIT (according to [cabal-dependency-licenses](https://github.com/jaspervdj/cabal-dependency-licenses)) and I don't expect that to change.
