### ISSUE TITLE
psa: build requires ghc 7.10

### ISSUE THREAD

**Issue by seanjensengrey** [jameysharp/corrode#39]
This is a meta-issue. As requiring GHC 7.10 isn't a problem. Readme should be updated.

I am super new to Haskell and attempted briefly to use GHC 8.0.1, the current version supplied by homebrew on OSX to build corrode, resulting in the following error:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: corrode-0.1.0.0 (user goal)
next goal: base (dependency of corrode-0.1.0.0)
rejecting: base-4.9.0.0/installed-4.9... (conflict: corrode => base>=4.8 &&
<4.9)
rejecting: base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
Dependency tree exhaustively searched.
```

For those using a Mac and homebrew, I have instructions here

https://gist.github.com/seanjensengrey/c423a5ab0276758030e74f501a63994f

that outline how to get the required tooling installed and corrode compiled.

**Comment by jameysharp** [comment]
Thanks for the report! I don't know of any reason it shouldn't work with GHC 8, so the dependency on `base` is probably just over-constrained. Does it work if you edit `corrode.cabal` and change both instances of `base >=4.8 && <4.9,` to `base >=4.8,`? That is, delete the upper version bound saying `&& <4.9`. If so, I'd love to get a pull request from you with that change.

Eventually I'll get Travis-CI or something set up and find out about these things automatically. :sweat:

**Comment by seanjensengrey** [comment]
I was able to make the change you suggested in a Linux VM. Didn't want to break my working OSX install. Corrode compiled and translated C into Rust.
