### ISSUE TITLE
Handle builtins

### ISSUE THREAD

**Issue by eternaleye** [jameysharp/corrode#49]
When trying to compile [LMDB](https://github.com/lmdb/lmdb) with CC=corrode:

```
("/usr/x86_64-pc-linux-gnu/include/bits/byteswap.h": line 47): illegal undefined variable; check whether a real C compiler accepts this:
    __builtin_bswap32
make: *** [Makefile:82: mdb.o] Error 1
```

A minimal approach might be to simply match against `__builtin_` (which is reserved), and pass them through unchanged. The resulting Rust code will fail to compile due to calling an undefined function, prompting the user to correct it.

**Comment by jameysharp** [comment]
Heh, I pushed commit 300e2bbd99b460e9fae11060b0fd192951068036 fixing this issue maybe half an hour before you filed it. :wink: Give it a try! You may well encounter some _other_ issues but hopefully this one is taken care of.
