### ISSUE TITLE
C99 struct initializer problem

### ISSUE THREAD

**Issue by waywardmonkeys** [jameysharp/corrode#83]
In the header, I have:

```c
typedef enum {
  TICKIT_MOUSEEV_PRESS = 1,
  TICKIT_MOUSEEV_DRAG,
  TICKIT_MOUSEEV_RELEASE,
  TICKIT_MOUSEEV_WHEEL,

  TICKIT_MOUSEEV_DRAG_START = 0x101,
  TICKIT_MOUSEEV_DRAG_OUTSIDE,
  TICKIT_MOUSEEV_DRAG_DROP,
  TICKIT_MOUSEEV_DRAG_STOP,
} TickitMouseEventType;

typedef struct {
  TickitMouseEventType type;
  int button;
  int mod;
  int line, col;
} TickitMouseEventInfo;
```

And in the C file, I have:

```c
      TickitMouseEventInfo draginfo = {
        .type   = TICKIT_MOUSEEV_DRAG_START,
        .button = root->mouse_last_button,
        .line   = root->mouse_last_line,
        .col    = root->mouse_last_col,
      };
```

This results in this error:

```
("window.c": line 148): illegal designator for field not in struct Struct9;
    check whether a real C compiler accepts this:
    .type
```

**Comment by jameysharp** [comment]
Oh, whoops, I think I broke renaming of identifiers that are reserved keywords in Rust, like `type`. Would you like to fix this bug?

The basic idea is to replace calls of `identToString` (from language-c) with calls to `applyRenames` (defined in `src/Language/Rust/Corrode/C.md`). The particular call that should fix your immediate bug is in `objectFromDesignators`, but I wouldn't be surprised if there are others.

**Comment by jameysharp** [comment]
Merged--Thank you!
