### ISSUE TITLE
Build error (invalid byte sequence) using stack

### ISSUE THREAD

**Issue by bryteise** [jameysharp/corrode#96]
While attempting to build b6699fb2fa552a07c6091276285a44133e5c9789 I run into the following (fresh stack setup shown because I'm not haskell literate):

$ stack setup  
Preparing to install GHC (tinfo6) to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-tinfo6-7.10.3.                                     
Installed GHC.                                                                            
stack will use a sandboxed GHC it installed
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec

$ stack install
[1 of 1] Compiling Main             ( /tmp/stack19605/Setup.hs, /tmp/stack19605/Setup.o )
Linking /home/wdouglas/.stack/setup-exe-cache/x86_64-linux-tinfo6/tmp-setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 ...
random-1.1: download
random-1.1: configure
primitive-0.6.1.0: download
base-compat-0.9.1: download
mtl-2.2.1: download
random-1.1: build
primitive-0.6.1.0: configure
primitive-0.6.1.0: build
base-compat-0.9.1: configure
base-compat-0.9.1: build
mtl-2.2.1: configure
mtl-2.2.1: build
base-compat-0.9.1: copy/register
markdown-unlit-0.4.0: download
markdown-unlit-0.4.0: configure
markdown-unlit-0.4.0: build
primitive-0.6.1.0: copy/register
mtl-2.2.1: copy/register
syb-0.6: download
syb-0.6: configure
random-1.1: copy/register
happy-1.19.5: download
syb-0.6: build
tf-random-0.5: download
happy-1.19.5: configure
markdown-unlit-0.4.0: copy/register
syb-0.6: copy/register
happy-1.19.5: build
tf-random-0.5: configure
tf-random-0.5: build
tf-random-0.5: copy/register
QuickCheck-2.8.2: download
QuickCheck-2.8.2: configure
QuickCheck-2.8.2: build
happy-1.19.5: copy/register
QuickCheck-2.8.2: copy/register
alex-3.1.7: download
alex-3.1.7: configure
alex-3.1.7: build
alex-3.1.7: copy/register
language-c-0.5.0: download
language-c-0.5.0: configure
language-c-0.5.0: build
language-c-0.5.0: copy/register
corrode-0.1.0.0: configure
Configuring corrode-0.1.0.0...
corrode-0.1.0.0: build
Preprocessing library corrode-0.1.0.0...
markdown-unlit: src/Language/Rust/Corrode/C.lhs: hGetContents: invalid argument (invalid byte sequence)
Completed 12 action(s).

--  While building package corrode-0.1.0.0 using:
      /home/wdouglas/.stack/setup-exe-cache/x86_64-linux-tinfo6/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-1.22.5.0 build lib:corrode exe:corrode --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1

**Comment by jameysharp** [comment]
Huh! Thanks for reporting this; I would not have expected this to happen.

I'm guessing your locale settings are not configured for UTF-8, and that the failing text is the accented "i" in "...A naïve translation of this idiom..." (It's line 3771 at the moment, but of course line numbers change all the time. It's immediately before the `interpretExpr` case for `CCast`.) I don't see any other non-ASCII characters in that file.

I guess the easiest fix is to quit being fancy and spell that word as "naive" like everyone else. :wink:

Would you check that changing that letter fixes the problem for you? If it does, I'd welcome a pull request with that fix in it, or I can make the appropriate commit myself if you'd prefer.

**Comment by bryteise** [comment]
Yep, I had a badly setup locale which this was oddly the first time I noticed having the system up for a month X(.
